//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.CompositeUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.CompositeUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Command adapter has already been bound to a command. 的本地化字符串。
        /// </summary>
        internal static string AdapterAlreadyBoundToACommand {
            get {
                return ResourceManager.GetString("AdapterAlreadyBoundToACommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The adapter has not been previously bound to the command. 的本地化字符串。
        /// </summary>
        internal static string AdapterNotBoundToGivenCommand {
            get {
                return ResourceManager.GetString("AdapterNotBoundToGivenCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddServices() method called for Module {0}. 的本地化字符串。
        /// </summary>
        internal static string AddServicesCalled {
            get {
                return ResourceManager.GetString("AddServicesCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This code is required by the smart part informations. 的本地化字符串。
        /// </summary>
        internal static string AutogeneratedCodeWarning {
            get {
                return ResourceManager.GetString("AutogeneratedCodeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception thrown in a background subscriber was not handled. The exception was {0}. 的本地化字符串。
        /// </summary>
        internal static string BackgroundSubscriberException {
            get {
                return ResourceManager.GetString("BackgroundSubscriberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A WorkItem cannot be added to itself. 的本地化字符串。
        /// </summary>
        internal static string CannotAddWorkItemToItself {
            get {
                return ResourceManager.GetString("CannotAddWorkItemToItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified event {0} was not found in the publisher. 的本地化字符串。
        /// </summary>
        internal static string CannotFindPublishedEvent {
            get {
                return ResourceManager.GetString("CannotFindPublishedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Command {0} cannot get an adapter for the type &quot;{1}&quot; 的本地化字符串。
        /// </summary>
        internal static string CannotGetCommandAdapter {
            get {
                return ResourceManager.GetString("CannotGetCommandAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Command &quot;{0}&quot; does not have access to the IAdapterMapService to perform the AddInvoker operation. 的本地化字符串。
        /// </summary>
        internal static string CannotGetMapService {
            get {
                return ResourceManager.GetString("CannotGetMapService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while loading the state with id {0} from the storage. 的本地化字符串。
        /// </summary>
        internal static string CannotLoadState {
            get {
                return ResourceManager.GetString("CannotLoadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscription {0}.{1} is static and is not supported. 的本地化字符串。
        /// </summary>
        internal static string CannotRegisterStaticSubscriptionMethods {
            get {
                return ResourceManager.GetString("CannotRegisterStaticSubscriptionMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while saving the state with id {0} to the storage. 的本地化字符串。
        /// </summary>
        internal static string CannotSaveState {
            get {
                return ResourceManager.GetString("CannotSaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot unregister site that was registered in parent: {0} 的本地化字符串。
        /// </summary>
        internal static string CannotUnregisterSiteRegisteredWithParent {
            get {
                return ResourceManager.GetString("CannotUnregisterSiteRegisteredWithParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adding command handler on {0} for command &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string CommandInjectionBuildUp {
            get {
                return ResourceManager.GetString("CommandInjectionBuildUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing command handler from {0} for command &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string CommandInjectionTearDown {
            get {
                return ResourceManager.GetString("CommandInjectionTearDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property marked as configuration property is not valid as its type {0} does not inherit from ApplicationSettingsBase. 的本地化字符串。
        /// </summary>
        internal static string ConfigurationAttributeOnValueWithIncompatibleType {
            get {
                return ResourceManager.GetString("ConfigurationAttributeOnValueWithIncompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings must be user-scoped in order to use the selected provider.  的本地化字符串。
        /// </summary>
        internal static string ConfigurationProviderMustBeUserScoped {
            get {
                return ResourceManager.GetString("ConfigurationProviderMustBeUserScoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This provider only supports settings classes defined in assemblies deployed locally. 的本地化字符串。
        /// </summary>
        internal static string ConfigurationProviderNotSupportLocation {
            get {
                return ResourceManager.GetString("ConfigurationProviderNotSupportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No default profile has been specified. 的本地化字符串。
        /// </summary>
        internal static string DefaultProfileNotSpecified {
            get {
                return ResourceManager.GetString("DefaultProfileNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add dependency for unknown module &apos;{0}&apos;; call AddModule() before AddDependency() 的本地化字符串。
        /// </summary>
        internal static string DependencyForUnknownModule {
            get {
                return ResourceManager.GetString("DependencyForUnknownModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A module declared a dependency on another module which is not declared to be loaded. Missing module(s): {0} 的本地化字符串。
        /// </summary>
        internal static string DependencyOnMissingModule {
            get {
                return ResourceManager.GetString("DependencyOnMissingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The dictionary is readonly and can not be modified. 的本地化字符串。
        /// </summary>
        internal static string DictionaryIsReadOnly {
            get {
                return ResourceManager.GetString("DictionaryIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A duplicated module with name {0} has been found by the loader. 的本地化字符串。
        /// </summary>
        internal static string DuplicatedModule {
            get {
                return ResourceManager.GetString("DuplicatedModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An object with this ID already exists: {0}. 的本地化字符串。
        /// </summary>
        internal static string DuplicateID {
            get {
                return ResourceManager.GetString("DuplicateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A service of this type already exists: {0}. 的本地化字符串。
        /// </summary>
        internal static string DuplicateService {
            get {
                return ResourceManager.GetString("DuplicateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A UI extension site with this name already exists: {0} 的本地化字符串。
        /// </summary>
        internal static string DuplicateUIExtensionSite {
            get {
                return ResourceManager.GetString("DuplicateUIExtensionSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception occurred while enumerating the modules using the {0} enumerator. 的本地化字符串。
        /// </summary>
        internal static string ErrorEnumeratingModules {
            get {
                return ResourceManager.GetString("ErrorEnumeratingModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while reading the solution profile {0}. 的本地化字符串。
        /// </summary>
        internal static string ErrorReadingProfile {
            get {
                return ResourceManager.GetString("ErrorReadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoker is not of type {0} 的本地化字符串。
        /// </summary>
        internal static string EventCommandAdapterInvokerNotType {
            get {
                return ResourceManager.GetString("EventCommandAdapterInvokerNotType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The event {0} on the invoker {1} is not present. 的本地化字符串。
        /// </summary>
        internal static string EventNotPresentOnInvoker {
            get {
                return ResourceManager.GetString("EventNotPresentOnInvoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One or more exceptions occurred while firing the topic &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string EventTopicFireException {
            get {
                return ResourceManager.GetString("EventTopicFireException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EventTopic {0} fire completed. 的本地化字符串。
        /// </summary>
        internal static string EventTopicTraceFireCompleted {
            get {
                return ResourceManager.GetString("EventTopicTraceFireCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exceptions occurred while firing the EventTopic {0}. 的本地化字符串。
        /// </summary>
        internal static string EventTopicTraceFireExceptions {
            get {
                return ResourceManager.GetString("EventTopicTraceFireExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Firing EventTopic {0} 的本地化字符串。
        /// </summary>
        internal static string EventTopicTraceFireStarted {
            get {
                return ResourceManager.GetString("EventTopicTraceFireStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publication for the EventTopic {0} was added for the event {1} on the type {2}. 的本地化字符串。
        /// </summary>
        internal static string EventTopicTracePublicationAdded {
            get {
                return ResourceManager.GetString("EventTopicTracePublicationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publication removed from EventTopic {0} for the event {1} on the type {2} 的本地化字符串。
        /// </summary>
        internal static string EventTopicTracePublicationRemoved {
            get {
                return ResourceManager.GetString("EventTopicTracePublicationRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscription for EventTopic {0} added for the method {1} on the type {2} 的本地化字符串。
        /// </summary>
        internal static string EventTopicTraceSubscriptionAdded {
            get {
                return ResourceManager.GetString("EventTopicTraceSubscriptionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscription on EventTopic {0} removed for the method {1} on the type {2} 的本地化字符串。
        /// </summary>
        internal static string EventTopicTraceSubscriptionRemoved {
            get {
                return ResourceManager.GetString("EventTopicTraceSubscriptionRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extension site does not exist: {0} 的本地化字符串。
        /// </summary>
        internal static string ExtensionSiteDoesNotExist {
            get {
                return ResourceManager.GetString("ExtensionSiteDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load module from assembly {0}. Error was:
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string FailedToLoadModule {
            get {
                return ResourceManager.GetString("FailedToLoadModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The adapter type is not a ICommandAdapter. 的本地化字符串。
        /// </summary>
        internal static string InvalidAdapter {
            get {
                return ResourceManager.GetString("InvalidAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is an error in the XML document. &lt;{0} xmlns=&apos;{1}&apos;&gt; was not expected. 的本地化字符串。
        /// </summary>
        internal static string InvalidCatalogXml {
            get {
                return ResourceManager.GetString("InvalidCatalogXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration section {0} must be of type {1}. 的本地化字符串。
        /// </summary>
        internal static string InvalidConfigurationSectionType {
            get {
                return ResourceManager.GetString("InvalidConfigurationSectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The UseCryptography setting must be set to a valid boolean value. 的本地化字符串。
        /// </summary>
        internal static string InvalidCryptographyValue {
            get {
                return ResourceManager.GetString("InvalidCryptographyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of the argument {0} provided for the enumeration {1} is invalid. 的本地化字符串。
        /// </summary>
        internal static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Catalog file path cannot be empty or null, and must be a local file under the application folder. 的本地化字符串。
        /// </summary>
        internal static string InvalidFileCatalogFilePath {
            get {
                return ResourceManager.GetString("InvalidFileCatalogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot open an isolated store with scope {0}. Check the IsolatedStorageFile documentation for the valid combination of values. 的本地化字符串。
        /// </summary>
        internal static string InvalidIsolatedStorageStatePersistanceParsedScope {
            get {
                return ResourceManager.GetString("InvalidIsolatedStorageStatePersistanceParsedScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scope value {0} is invalid. {1} does not exist in the IsolatedStorageScope enumeration. 的本地化字符串。
        /// </summary>
        internal static string InvalidIsolatedStorageStatePersistanceScope {
            get {
                return ResourceManager.GetString("InvalidIsolatedStorageStatePersistanceScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value for the PublicationScope is invalid. 的本地化字符串。
        /// </summary>
        internal static string InvalidPublicationScope {
            get {
                return ResourceManager.GetString("InvalidPublicationScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publication event {0}.{1} must have a delegate type compatible with EventHandler or EventHandler&lt;T&gt;. 的本地化字符串。
        /// </summary>
        internal static string InvalidPublicationSignature {
            get {
                return ResourceManager.GetString("InvalidPublicationSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Catalog file path {0} is not a local file under the application folder {1}. 的本地化字符串。
        /// </summary>
        internal static string InvalidSolutionProfilePath {
            get {
                return ResourceManager.GetString("InvalidSolutionProfilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is an error in the XML document. &lt;{0} xmlns=&apos;{1}&apos;&gt; was not expected. 的本地化字符串。
        /// </summary>
        internal static string InvalidSolutionProfileXml {
            get {
                return ResourceManager.GetString("InvalidSolutionProfileXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State stream from storage is invalid. 的本地化字符串。
        /// </summary>
        internal static string InvalidStateStream {
            get {
                return ResourceManager.GetString("InvalidStateStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscription method {0}.{1} must have a signature receiving an object and an EventArgs parameter (EventHandler or EventHandler&lt;T&gt; delegates signature). 的本地化字符串。
        /// </summary>
        internal static string InvalidSubscriptionSignature {
            get {
                return ResourceManager.GetString("InvalidSubscriptionSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module {0} added to the container. 的本地化字符串。
        /// </summary>
        internal static string LogModuleAdded {
            get {
                return ResourceManager.GetString("LogModuleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded assembly file {0} for Module. 的本地化字符串。
        /// </summary>
        internal static string LogModuleAssemblyLoaded {
            get {
                return ResourceManager.GetString("LogModuleAssemblyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly file {0} was not found. 的本地化字符串。
        /// </summary>
        internal static string ModuleNotFound {
            get {
                return ResourceManager.GetString("ModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly path {0} does not fall under the current application root. 的本地化字符串。
        /// </summary>
        internal static string ModulePathNotUnderRoot {
            get {
                return ResourceManager.GetString("ModulePathNotUnderRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load() method called for Module {0}. 的本地化字符串。
        /// </summary>
        internal static string ModuleStartCalled {
            get {
                return ResourceManager.GetString("ModuleStartCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No UIElementAdapterFactory register for type {0}. 的本地化字符串。
        /// </summary>
        internal static string NoRegisteredUIElementFactory {
            get {
                return ResourceManager.GetString("NoRegisteredUIElementFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing WorkItems is not permitted. Use WorkItem.Terminate or WorkItem.Dispose to clean up a WorkItem. 的本地化字符串。
        /// </summary>
        internal static string NoRemoveWorkItemFromManagedObjectCollection {
            get {
                return ResourceManager.GetString("NoRemoveWorkItemFromManagedObjectCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service implementation {0} returned a null reader for the catalog. 的本地化字符串。
        /// </summary>
        internal static string NullReaderReturned {
            get {
                return ResourceManager.GetString("NullReaderReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ModuleEnumerator implementation {0} returned a null reader for the catalog. 的本地化字符串。
        /// </summary>
        internal static string NullSolutionProfileReaderReturned {
            get {
                return ResourceManager.GetString("NullSolutionProfileReaderReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add more than one instance of the same publisher to one topic. 的本地化字符串。
        /// </summary>
        internal static string OnlyOnePublicationIsAllowed {
            get {
                return ResourceManager.GetString("OnlyOnePublicationIsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile {0} was not found in the catalog. 的本地化字符串。
        /// </summary>
        internal static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile {0} was not found in the catalog. 的本地化字符串。
        /// </summary>
        internal static string ProfileNotFoundInCatalog {
            get {
                return ResourceManager.GetString("ProfileNotFoundInCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception occurred while reading the profile. 的本地化字符串。
        /// </summary>
        internal static string ReadProfileException {
            get {
                return ResourceManager.GetString("ReadProfileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ModuleLoaderService cannot initialize the module because some of their dependencies are not present. Make sure to deploy all the assemblies needed to execute the module. 的本地化字符串。
        /// </summary>
        internal static string ReferencedAssemblyNotFound {
            get {
                return ResourceManager.GetString("ReferencedAssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing Commands from WorkItem is not permitted. An attempt was made to remove the command {0}. 的本地化字符串。
        /// </summary>
        internal static string RemoveCommandFromWorkItemIsNotPermitted {
            get {
                return ResourceManager.GetString("RemoveCommandFromWorkItemIsNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing EventTopic from WorkItem is not permitted. An attempt was made to remove the EventTopic {0}. 的本地化字符串。
        /// </summary>
        internal static string RemoveEventTopicFromWorkItemIsNotPermitted {
            get {
                return ResourceManager.GetString("RemoveEventTopicFromWorkItemIsNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service {1} added for Module {0}. 的本地化字符串。
        /// </summary>
        internal static string ServiceAdded {
            get {
                return ResourceManager.GetString("ServiceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service {1} will be added on demand for Module {0}. 的本地化字符串。
        /// </summary>
        internal static string ServiceAddedOnDemand {
            get {
                return ResourceManager.GetString("ServiceAddedOnDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service {0}, required for component {1} is not available in the current context. 的本地化字符串。
        /// </summary>
        internal static string ServiceMissingExceptionMessage {
            get {
                return ResourceManager.GetString("ServiceMissingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service {0} is not available in the current context. 的本地化字符串。
        /// </summary>
        internal static string ServiceMissingExceptionSimpleMessage {
            get {
                return ResourceManager.GetString("ServiceMissingExceptionSimpleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Implement ISmartPartInfoProvider in the containing smart part. Required in order for contained smart part infos to work. 的本地化字符串。
        /// </summary>
        internal static string SmartPartMustImplementISmartPartInfoProvider {
            get {
                return ResourceManager.GetString("SmartPartMustImplementISmartPartInfoProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The smartpart is not present in the workspace. 的本地化字符串。
        /// </summary>
        internal static string SmartPartNotInWorkspace {
            get {
                return ResourceManager.GetString("SmartPartNotInWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Catalog file at location {0} could not be found. 的本地化字符串。
        /// </summary>
        internal static string SolutionProfileNotFound {
            get {
                return ResourceManager.GetString("SolutionProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no state persisted with the given id {0}. 的本地化字符串。
        /// </summary>
        internal static string StateDoesNotExist {
            get {
                return ResourceManager.GetString("StateDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Static command handler &quot;{0}&quot; is not supported. 的本地化字符串。
        /// </summary>
        internal static string StaticCommandHandlerNotSupported {
            get {
                return ResourceManager.GetString("StaticCommandHandlerNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Static command publisher &quot;{0}&quot; is not supported. 的本地化字符串。
        /// </summary>
        internal static string StaticCommandPublisherNotSupported {
            get {
                return ResourceManager.GetString("StaticCommandPublisherNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registering static event {0} as topic publication is not allowed. 的本地化字符串。
        /// </summary>
        internal static string StaticPublisherNotAllowed {
            get {
                return ResourceManager.GetString("StaticPublisherNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided String argument {0} must not be empty. 的本地化字符串。
        /// </summary>
        internal static string StringCannotBeEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified method handler {0} is not present or accessible on the subscriber type {1}. 的本地化字符串。
        /// </summary>
        internal static string SubscriberHandlerNotFound {
            get {
                return ResourceManager.GetString("SubscriberHandlerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Command {0} has been executed. 的本地化字符串。
        /// </summary>
        internal static string TraceCommandExecuted {
            get {
                return ResourceManager.GetString("TraceCommandExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command status for command {0} has changed to {1}. 的本地化字符串。
        /// </summary>
        internal static string TraceCommandStatusChanged {
            get {
                return ResourceManager.GetString("TraceCommandStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The state with ID {0} has changed. The changed value was {1}. 的本地化字符串。
        /// </summary>
        internal static string TraceStateChangedMessage {
            get {
                return ResourceManager.GetString("TraceStateChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The work item {0} has been run. 的本地化字符串。
        /// </summary>
        internal static string TraceWorkItemRun {
            get {
                return ResourceManager.GetString("TraceWorkItemRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkItem {0} Run method has started. 的本地化字符串。
        /// </summary>
        internal static string TraceWorkItemRunStarted {
            get {
                return ResourceManager.GetString("TraceWorkItemRunStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The work item {0} is Activating. 的本地化字符串。
        /// </summary>
        internal static string TraceWorkItemStatusActivating {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusActivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The work item {0} is Activated. 的本地化字符串。
        /// </summary>
        internal static string TraceWorkItemStatusChangedToActivated {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusChangedToActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The work item {0} is Deactivated. 的本地化字符串。
        /// </summary>
        internal static string TraceWorkItemStatusChangedToDeactivated {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusChangedToDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The work item {0} is Disposed. 的本地化字符串。
        /// </summary>
        internal static string TraceWorkItemStatusChangedToDisposed {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusChangedToDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The work item {0} is Initialized. 的本地化字符串。
        /// </summary>
        internal static string TraceWorkItemStatusChangedToInitialized {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusChangedToInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The work item {0} is Terminated. 的本地化字符串。
        /// </summary>
        internal static string TraceWorkItemStatusChangedToTerminated {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusChangedToTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The work item {0} is Deactivating. 的本地化字符串。
        /// </summary>
        internal static string TraceWorkItemStatusDeactivating {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusDeactivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The work item {0} is Terminating. 的本地化字符串。
        /// </summary>
        internal static string TraceWorkItemStatusTerminating {
            get {
                return ResourceManager.GetString("TraceWorkItemStatusTerminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided type {0} is not compatible with {1}. 的本地化字符串。
        /// </summary>
        internal static string TypeNotCompatible {
            get {
                return ResourceManager.GetString("TypeNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI element must be a {0} 的本地化字符串。
        /// </summary>
        internal static string UIElementNotCorrectType {
            get {
                return ResourceManager.GetString("UIElementNotCorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smart part type {0} is not supported. Expected {1} or a compatible type. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedSmartPartType {
            get {
                return ResourceManager.GetString("UnsupportedSmartPartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The visualizer has already been initialized. 的本地化字符串。
        /// </summary>
        internal static string VisualizerAlreadyInitialized {
            get {
                return ResourceManager.GetString("VisualizerAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visualizer type must implement IVisualizer. 的本地化字符串。
        /// </summary>
        internal static string VisualizerMustImplementIVisualizer {
            get {
                return ResourceManager.GetString("VisualizerMustImplementIVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not modify this method, changes will be lost upon regeneration by the designer. 的本地化字符串。
        /// </summary>
        internal static string WorkItemDesignerCodeWarning {
            get {
                return ResourceManager.GetString("WorkItemDesignerCodeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialized WorkItem extension {0} with WorkItem {1}. 的本地化字符串。
        /// </summary>
        internal static string WorkItemExtensionInitialized {
            get {
                return ResourceManager.GetString("WorkItemExtensionInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registered WorkItem extension type {0} for WorkItem type {1}. 的本地化字符串。
        /// </summary>
        internal static string WorkItemExtensionRegistered {
            get {
                return ResourceManager.GetString("WorkItemExtensionRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registered WorkItem extension type {0} for root WorkItem. 的本地化字符串。
        /// </summary>
        internal static string WorkItemExtensionRootRegistered {
            get {
                return ResourceManager.GetString("WorkItemExtensionRootRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The WorkItem Extension type {0} is already registered for WorkItem type {1}. 的本地化字符串。
        /// </summary>
        internal static string WorkItemExtensionTypeAlreadyRegistered {
            get {
                return ResourceManager.GetString("WorkItemExtensionTypeAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkItem has already been disposed or terminated. 的本地化字符串。
        /// </summary>
        internal static string WorkItemTerminated {
            get {
                return ResourceManager.GetString("WorkItemTerminated", resourceCulture);
            }
        }
    }
}
