//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.ObjectBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.ObjectBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Object builder has no strategies. 的本地化字符串。
        /// </summary>
        internal static string BuilderHasNoStrategies {
            get {
                return ResourceManager.GetString("BuilderHasNoStrategies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] {1} / {2} :: {3} 的本地化字符串。
        /// </summary>
        internal static string BuilderStrategyTraceBuildUp {
            get {
                return ResourceManager.GetString("BuilderStrategyTraceBuildUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] {1} :: {2} 的本地化字符串。
        /// </summary>
        internal static string BuilderStrategyTraceTearDown {
            get {
                return ResourceManager.GetString("BuilderStrategyTraceTearDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [BuilderBase] Finished BuildUp on {0} with ID {1} 的本地化字符串。
        /// </summary>
        internal static string BuildUpFinished {
            get {
                return ResourceManager.GetString("BuildUpFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [BuilderBase] Starting BuildUp on {0} with ID {1} 的本地化字符串。
        /// </summary>
        internal static string BuildUpStarting {
            get {
                return ResourceManager.GetString("BuildUpStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calling constructor({0}) 的本地化字符串。
        /// </summary>
        internal static string CallingConstructor {
            get {
                return ResourceManager.GetString("CallingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calling method {0}({1}) 的本地化字符串。
        /// </summary>
        internal static string CallingMethod {
            get {
                return ResourceManager.GetString("CallingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calling IBuilderAware.OnBuiltUp() 的本地化字符串。
        /// </summary>
        internal static string CallingOnBuiltUp {
            get {
                return ResourceManager.GetString("CallingOnBuiltUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calling IBuilderAware.OnTearingDown() 的本地化字符串。
        /// </summary>
        internal static string CallingOnTearingDown {
            get {
                return ResourceManager.GetString("CallingOnTearingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting property {0}({1}) 的本地化字符串。
        /// </summary>
        internal static string CallingProperty {
            get {
                return ResourceManager.GetString("CallingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not create an instance of type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string CannotCreateInstanceOfType {
            get {
                return ResourceManager.GetString("CannotCreateInstanceOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In class &apos;{0}&apos;, cannot inject value on property &apos;{1}&apos; because it is read-only. 的本地化字符串。
        /// </summary>
        internal static string CannotInjectReadOnlyProperty {
            get {
                return ResourceManager.GetString("CannotInjectReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not locate dependency &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string DependencyMissing {
            get {
                return ResourceManager.GetString("DependencyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many dependency injection attributes defined on {0}.{1}. 的本地化字符串。
        /// </summary>
        internal static string InvalidAttributeCombination {
            get {
                return ResourceManager.GetString("InvalidAttributeCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid enumeration value. 的本地化字符串。
        /// </summary>
        internal static string InvalidEnumerationValue {
            get {
                return ResourceManager.GetString("InvalidEnumerationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An item with the given key is already present in the dictionary. 的本地化字符串。
        /// </summary>
        internal static string KeyAlreadyPresentInDictionary {
            get {
                return ResourceManager.GetString("KeyAlreadyPresentInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing policy to build {0} named &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MissingPolicyNamed {
            get {
                return ResourceManager.GetString("MissingPolicyNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing policy to build unnamed {0}. 的本地化字符串。
        /// </summary>
        internal static string MissingPolicyUnnamed {
            get {
                return ResourceManager.GetString("MissingPolicyUnnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find an appropriately matching constructor. 的本地化字符串。
        /// </summary>
        internal static string NoAppropriateConstructor {
            get {
                return ResourceManager.GetString("NoAppropriateConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registered as singleton 的本地化字符串。
        /// </summary>
        internal static string SingletonRegistered {
            get {
                return ResourceManager.GetString("SingletonRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returning existing singleton 的本地化字符串。
        /// </summary>
        internal static string SingletonReturned {
            get {
                return ResourceManager.GetString("SingletonReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [BuilderBase] Finished TearDown on {0} 的本地化字符串。
        /// </summary>
        internal static string TearDownFinished {
            get {
                return ResourceManager.GetString("TearDownFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [BuilderBase] Starting TearDown on {0} 的本地化字符串。
        /// </summary>
        internal static string TearDownStarting {
            get {
                return ResourceManager.GetString("TearDownStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapped to {0} / {1} 的本地化字符串。
        /// </summary>
        internal static string TypeMapped {
            get {
                return ResourceManager.GetString("TypeMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 While resolving dependencies for {2}, the provided type {1} is not compatible with {0}. 的本地化字符串。
        /// </summary>
        internal static string TypeNotCompatible {
            get {
                return ResourceManager.GetString("TypeNotCompatible", resourceCulture);
            }
        }
    }
}
